name: jupyter
channels:
- conda-forge
- pytorch
dependencies:
- cpuonly
- nb_conda::conda-forge
- nb_conda_kernels::conda-forge
- notebook::conda-forge
- python=3.11
- pytorch==2.1.2::pytorch
- torchaudio==2.1.2::pytorch
- torchvision==0.16.2::pytorch

